# Generated by Django 3.1.2 on 2020-10-07 08:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^([a-zA-Z]{2,20})$', 'only a-z and A-Z min-3 max-20')])),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^([a-zA-Z]{2,20})$', 'only a-z and A-Z min-3 max-20')])),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='office.officemodel')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
